server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
#    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: bank-app

  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: DEBUG

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration: ${JWT_EXPIRATION}







