server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    #    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: bank-app

  datasource:
    url: ${DATABASE_URL}  # Using the environment variable for the database URL
#    url: "jdbc:postgresql://alexanderemmanuel1719:NBH1lDt5hOIA@ep-calm-sound-a572wcmv.us-east-2.aws.neon.tech/bank?sslmode=require"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: DEBUG

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration: ${JWT_EXPIRATION}
